const tudosokData = [
  { id: 1, nev: 'Ádám Veronika', terulet: 'természettudományok' },
  { id: 2, nev: 'Agócs Zoltán', terulet: 'műszaki tudományok' },
  { id: 3, nev: 'Almár Iván', terulet: 'természettudományok' },
  { id: 4, nev: 'Andrásfalvy Bertalan', terulet: 'bölcsésztudományok' },
  { id: 5, nev: 'Balázs Ervin', terulet: 'agrártudományok' },
  { id: 6, nev: 'Bán Zsófia', terulet: 'bölcsésztudományok' },
  { id: 7, nev: 'Barabási Albert-László', terulet: 'természettudományok' },
  { id: 8, nev: 'Bartholy Judit', terulet: 'természettudományok' },
  { id: 9, nev: 'Békesi László', terulet: 'társadalomtudományok' },
  { id: 10, nev: 'Bence György', terulet: 'társadalomtudományok' },
  { id: 11, nev: 'Bencze Gyula', terulet: 'természettudományok' },
  { id: 12, nev: 'Berend T. Iván', terulet: 'társadalomtudományok' },
  { id: 13, nev: 'Besznyák István', terulet: 'orvostudományok' },
  { id: 14, nev: 'Bihari Mihály', terulet: 'társadalomtudományok' },
  { id: 15, nev: 'Bodó Balázs', terulet: 'természettudományok' },
  { id: 17, nev: 'Bókay Antal', terulet: 'bölcsésztudományok' },
  { id: 18, nev: 'Bor Zsolt', terulet: 'természettudományok' },
  { id: 19, nev: 'Borhidi Attila', terulet: 'természettudományok' },
  { id: 20, nev: 'Borsos Antal', terulet: 'orvostudományok' },
  { id: 21, nev: 'Cerf, Vint', terulet: 'műszaki tudományok' },
  { id: 22, nev: 'Czvikovszky Tibor', terulet: 'műszaki tudományok' },
  { id: 23, nev: 'Csányi Vilmos', terulet: 'természettudományok' },
  { id: 24, nev: 'Csépe Valéria', terulet: 'bölcsésztudományok' },
  { id: 25, nev: 'Csermely Péter', terulet: 'természettudományok' },
  { id: 26, nev: 'Csiba László', terulet: 'orvostudományok' },
  { id: 27, nev: 'Damjanovich Sándor', terulet: 'orvostudományok' },
  { id: 28, nev: 'Detrekői Ákos', terulet: 'természettudományok' },
  { id: 29, nev: 'Dudits Dénes', terulet: 'természettudományok' },
  { id: 30, nev: 'Erdei Anna', terulet: 'orvostudományok' },
  { id: 31, nev: 'Erdő Péter', terulet: 'hittudomány' },
  { id: 32, nev: 'Schweitzer József', terulet: 'hittudomány' },
  { id: 33, nev: 'Esterházy Péter', terulet: 'bölcsésztudományok' },
  { id: 34, nev: 'Faigel Gyula', terulet: 'természettudományok' },
  { id: 35, nev: 'Falus András', terulet: 'természettudományok' },
  { id: 36, nev: 'Faragó Sándor', terulet: 'természettudományok' },
  { id: 37, nev: 'Ferge Zsuzsa', terulet: 'társadalomtudományok' },
  { id: 38, nev: 'Fésüs László', terulet: 'orvostudományok' },
  { id: 39, nev: 'Fodor Zoltán', terulet: 'természettudományok' },
  { id: 40, nev: 'Forray R. Katalin', terulet: 'társadalomtudományok' },
  { id: 41, nev: 'Freund Tamás', terulet: 'természettudományok' },
  { id: 42, nev: 'Furka Árpád', terulet: 'orvostudományok' },
  { id: 43, nev: 'Gáncs Péter', terulet: 'hittudomány' },
  { id: 44, nev: 'Szabó István', terulet: 'hittudomány' },
  { id: 45, nev: 'Gángó Gábor', terulet: 'bölcsésztudományok' },
  { id: 46, nev: 'Görömbei András', terulet: 'bölcsésztudományok' },
  { id: 47, nev: 'Gráf László', terulet: 'természettudományok' },
  { id: 48, nev: 'Gulyás Balázs', terulet: 'orvostudományok' },
  { id: 49, nev: 'Gyarmati György', terulet: 'bölcsésztudományok' },
  { id: 50, nev: 'Györfi László', terulet: 'természettudományok' },
  { id: 51, nev: 'Gyulai József', terulet: 'természettudományok' },
  { id: 52, nev: 'Hámori József', terulet: 'természettudományok' },
  { id: 53, nev: 'Havass Miklós', terulet: 'műszaki tudományok' },
  { id: 54, nev: 'Heller Ágnes', terulet: 'bölcsésztudományok' },
  { id: 55, nev: 'Heszky László', terulet: 'természettudományok' },
  { id: 56, nev: 'Horn Péter', terulet: 'agrártudományok' },
  { id: 57, nev: 'Horváth Attila', terulet: 'orvostudományok' },
  { id: 58, nev: 'Horváth Iván', terulet: 'bölcsésztudományok' },
  { id: 59, nev: 'Horváth Zalán', terulet: 'természettudományok' },
  { id: 60, nev: 'Hunyady György', terulet: 'bölcsésztudományok' },
  { id: 61, nev: 'Iván László', terulet: 'orvostudományok' },
  { id: 62, nev: 'Jaksity György', terulet: 'társadalomtudományok' },
  { id: 63, nev: 'Janka Zoltán', terulet: 'orvostudományok' },
  { id: 64, nev: 'Járay Jenő', terulet: 'orvostudományok' },
  { id: 65, nev: 'Jéki László', terulet: 'természettudományok' },
  { id: 66, nev: 'Jermendy György', terulet: 'orvostudományok' },
  { id: 67, nev: 'Kállai Gábor', terulet: 'társadalomtudományok' },
  { id: 68, nev: 'Kálmán Erika', terulet: 'természettudományok' },
  { id: 69, nev: 'Kampis György', terulet: 'természettudományok' },
  { id: 70, nev: 'Karádi István', terulet: 'orvostudományok' },
  { id: 71, nev: 'Katona Gyula', terulet: 'természettudományok' },
  { id: 72, nev: 'Király Béla', terulet: 'bölcsésztudományok' },
  { id: 73, nev: 'Klaniczay Gábor', terulet: 'bölcsésztudományok' },
  { id: 74, nev: 'Klement Zoltán', terulet: 'természettudományok' },
  { id: 75, nev: 'Kolláth Zoltán', terulet: 'természettudományok' },
  { id: 76, nev: 'Kolosi Tamás', terulet: 'társadalomtudományok' },
  { id: 77, nev: 'Kondor Imre', terulet: 'társadalomtudományok' },
  { id: 78, nev: 'Kornai János', terulet: 'társadalomtudományok' },
  { id: 79, nev: 'Kósa Éva', terulet: 'bölcsésztudományok' },
  { id: 80, nev: 'Kosztolányi György', terulet: 'orvostudományok' },
  { id: 81, nev: 'Kovács Ferenc', terulet: 'műszaki tudományok' },
  { id: 82, nev: 'Kovács Ilona', terulet: 'bölcsésztudományok' },
  { id: 83, nev: 'Kroó Norbert', terulet: 'természettudományok' },
  { id: 85, nev: 'Kun Miklós', terulet: 'bölcsésztudományok' },
  { id: 86, nev: 'Laczkovich Miklós', terulet: 'természettudományok' },
  { id: 87, nev: 'Lámfalussy Sándor', terulet: 'társadalomtudományok' },
  { id: 88, nev: 'Láng István', terulet: 'természettudományok' },
  { id: 89, nev: 'Lovász László', terulet: 'természettudományok' },
  { id: 90, nev: 'Lukacs, John', terulet: 'bölcsésztudományok' },
  { id: 91, nev: 'Makovecz Imre', terulet: 'műszaki tudományok' },
  { id: 92, nev: 'Máray Tamás', terulet: 'műszaki tudományok' },
  { id: 93, nev: 'Marosi Ernő', terulet: 'bölcsésztudományok' },
  { id: 94, nev: 'Maróth Miklós', terulet: 'bölcsésztudományok' },
  { id: 95, nev: 'Meskó Attila', terulet: 'természettudományok' },
  { id: 97, nev: 'Mézes Lili', terulet: 'természettudományok' },
  { id: 98, nev: 'Mészáros Ernő', terulet: 'természettudományok' },
  { id: 99, nev: 'Mihály György', terulet: 'természettudományok' },
  { id: 100, nev: 'Nádasdy Ádám', terulet: 'bölcsésztudományok' },
  { id: 101, nev: 'Nagy Károly', terulet: 'természettudományok' },
  { id: 102, nev: 'Nékám Kristóf', terulet: 'orvostudományok' },
  { id: 103, nev: 'Nyíri Kristóf', terulet: 'bölcsésztudományok' },
  { id: 104, nev: 'Ormos Mária', terulet: 'bölcsésztudományok' },
  { id: 105, nev: 'Ormos Pál', terulet: 'természettudományok' },
  { id: 106, nev: 'Palánkai Tibor', terulet: 'társadalomtudományok' },
  { id: 107, nev: 'Palkovics László', terulet: 'műszaki tudományok' },
  { id: 108, nev: 'Palló Gábor', terulet: 'természettudományok' },
  { id: 109, nev: 'Pap László', terulet: 'műszaki tudományok' },
  { id: 110, nev: 'Papp Zoltán', terulet: 'orvostudományok' },
  { id: 111, nev: 'Patkós András', terulet: 'természettudományok' },
  { id: 112, nev: 'Petrovay Kristóf', terulet: 'természettudományok' },
  { id: 113, nev: 'Pléh Csaba', terulet: 'bölcsésztudományok' },
  { id: 114, nev: 'Pongor Sándor', terulet: 'természettudományok' },
  { id: 115, nev: 'Pucsok József', terulet: 'orvostudományok' },
  { id: 116, nev: 'Radnóti Sándor', terulet: 'bölcsésztudományok' },
  { id: 117, nev: 'Rajnavölgyi Éva', terulet: 'orvostudományok' },
  { id: 118, nev: 'Raskó István', terulet: 'természettudományok' },
  { id: 119, nev: 'Rechnitzer János', terulet: 'társadalomtudományok' },
  { id: 120, nev: 'Rényi András', terulet: 'bölcsésztudományok' },
  { id: 121, nev: 'Romsics Ignác', terulet: 'bölcsésztudományok' },
  { id: 122, nev: 'Róna-Tas András', terulet: 'bölcsésztudományok' },
  { id: 123, nev: 'Rónyai Lajos', terulet: 'természettudományok' },
  { id: 124, nev: 'Roska Tamás', terulet: 'műszaki tudományok' },
  { id: 125, nev: 'Sajó András', terulet: 'társadalomtudományok' },
  { id: 126, nev: 'Schaff Zsuzsa', terulet: 'orvostudományok' },
  { id: 127, nev: 'Sohár Pál', terulet: 'természettudományok' },
  { id: 128, nev: 'Sólyom Jenő', terulet: 'természettudományok' },
  { id: 129, nev: 'Sólyom László', terulet: 'társadalomtudományok' },
  { id: 130, nev: 'Somfai László', terulet: 'művészetek' },
  { id: 131, nev: 'Somlyódy László', terulet: 'természettudományok' },
  { id: 132, nev: 'Sótonyi Péter Tamás', terulet: 'agrártudományok' },
  { id: 133, nev: 'Spiró György', terulet: 'bölcsésztudományok' },
  { id: 134, nev: 'Szabad János', terulet: 'természettudományok' },
  { id: 135, nev: 'Szabó Csaba', terulet: 'orvostudományok' },
  { id: 136, nev: 'Szabó Gábor', terulet: 'természettudományok' },
  { id: 138, nev: 'Szabó Miklós', terulet: 'társadalomtudományok' },
  { id: 139, nev: 'Szabó Miklós', terulet: 'bölcsésztudományok' },
  { id: 140, nev: 'Szántay Csaba', terulet: 'természettudományok' },
  { id: 141, nev: 'Száz János', terulet: 'társadalomtudományok' },
  { id: 142, nev: 'Szegedy-Maszák Mihály', terulet: 'bölcsésztudományok' },
  { id: 143, nev: 'Szegő Károly', terulet: 'természettudományok' },
  { id: 144, nev: 'Szilágyi N. Sándor', terulet: 'bölcsésztudományok' },
  { id: 145, nev: 'Tamás Gábor', terulet: 'orvostudományok' },
  { id: 146, nev: 'Tombor Antal', terulet: 'műszaki tudományok' },
  { id: 147, nev: 'Tompa Anna', terulet: 'orvostudományok' },
  { id: 148, nev: 'Tóth József', terulet: 'társadalomtudományok' },
  { id: 149, nev: 'Tringer László', terulet: 'bölcsésztudományok' },
  { id: 150, nev: 'Tulassay Tivadar', terulet: 'orvostudományok' },
  { id: 151, nev: 'Varga János', terulet: 'agrártudományok' },
  { id: 152, nev: 'Varga Zoltán', terulet: 'természettudományok' },
  { id: 153, nev: 'Vásáry Tamás', terulet: 'művészetek' },
  { id: 154, nev: 'Vékás Lajos', terulet: 'társadalomtudományok' },
  { id: 155, nev: 'Venetianer Pál', terulet: 'természettudományok' },
  { id: 156, nev: 'Vicsek Tamás', terulet: 'természettudományok' },
  { id: 157, nev: 'Vidor Ferenc', terulet: 'műszaki tudományok' },
  { id: 158, nev: 'Vígh László', terulet: 'természettudományok' },
  { id: 159, nev: 'Vissy Károly', terulet: 'természettudományok' },
  { id: 160, nev: 'Vizi E. Szilveszter', terulet: 'orvostudományok' },
  { id: 162, nev: 'Vonderviszt Ferenc', terulet: 'természettudományok' },
  { id: 163, nev: 'Werner, Wendelin', terulet: 'természettudományok' },
  { id: 164, nev: 'Závodszky Péter', terulet: 'természettudományok' },
  { id: 165, nev: 'Zoletnik Sándor', terulet: 'természettudományok' },
  { id: 166, nev: 'Zrínyi Miklós', terulet: 'műszaki tudományok' },
];
